### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by mostafa-saad** [Ali-Elbana/Mastering-4-critical-SKILLS-using-CPP17#1]
Hey,

It harms me that you expose all the homework and solutions of my course this way. These are key ingredients of the course.

May I suggest you remove all references to the course name so that people can't find it. Also please any document explaining the homework/assignment to be removed.

I appreciate if you can do so

**Comment by Ali-Elbana** [comment]
Peace upon you Dr/ Mostafa,

Firstly, I want to apologize that I don't know that's not allowed.

I will remove all the slides from GitHub and LinkedIn.

I want to make sure about my solutions of the problems and projects, Is it
ok to be shared or not?

Finally, I want to apologize again for my unawareness and I wish you accept
it, it's really hard to me to know that I harm you.


Sincerely,

Ali Adel Mohammed Ali
***@***.***
(+20)1019949256

**Comment by mostafa-saad** [comment]
Thanks a lot

If you hide the course name and the pdfs, feel free to leave them
